project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  repo-url: https://github.com/pommevilla/germs.dsc
  title: "GERMS-DS"
  toc: true
  
  page-navigation: true
    
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: "GERMS Lab"
        url: "http://germslab.org"
      
  sidebar: 
    style: docked
    contents: 
      - href: index.qmd
        text: "Home"
      - section: "Meetings"
        contents:
          - docs/meetings/getting_started.qmd
          - docs/meetings/first_model.qmd
      - about.qmd

format:
  html:
    code-copy: true
    code-block-bg: true
    theme: cosmo
    css: styles/styles.scss
    toc: true
    



