---
title: "GERMS-DS"
date: last-modified
---

The goal of the GERMS-DS is to walk GERMS lab members through a data science project. The analysis part of a data science project is obviously important, so we'll walk through cleaning/transforming data, formulating questions, creating visualizations, and doing predictions/statistical tests where appropriate. However, we'll walk through all the other parts of doing analysis that is talked about less, like how to use Git to version your work, how to structure your directory, how to organize your code, and how to share your work online. 

# Schedule

The first GERMS-DS meeting is on Monday, April 11 at  9AM in Elings 4321. Future meetings will be held every other Monday at the same time. 

# What you need to get started

* Install [R](https://cran.r-project.org/bin/windows/base/) and the latest version of [RStudio](https://www.rstudio.com/products/rstudio/download/)
* Install [Quarto](https://quarto.org/docs/get-started/)
* Install the `tidyverse`, `tidymodels`, `rmarkdown`, `janitor`, `lubridate`, and `readxl` libraries


